fsudo: required
dist: trusty
language: cpp
compiler:
- gcc
script:
- export VBCC=${HOME}/vbcc
- mkdir -p ${VBCC}/bin
- wget http://sun.hasenbraten.de/vasm/release/vasm.tar.gz
- tar xzvf vasm.tar.gz
- pushd vasm 
- make CPU=m68k SYNTAX=mot
- cp vasmm68k_mot vobjdump ${VBCC}/bin
- popd
- export PATH=${VBCC}/bin:${PATH}
- vasmm68k_mot -kick1hunks -Fhunkexe -o test -nosym ./RipFiles.s
